<?php

// autoload.php @generated by Composer
class Autoload {
	public function __construct(){
		require_once __DIR__ . '/composer/autoload_real.php';

		return ComposerAutoloaderInit08c645151609833f29ab79143713d0b5::getLoader();
	}
}
